baseURL = "https://blog.floatingminds.ink"
title = "漂浮的思绪"
theme = "etch"
languageCode = "en-zh"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Peng He's blog"
  copyright = "Copyright © 2020 Floating Minds Peng He"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
