baseURL = "/"
title = "Floating Minds"
theme = "hugo-xmin"
languageCode = "zh-CN"

[params]
  description = "Tech and other stuff"
  footer= "&copy; Peng He 2023 -- {Year} | [Github](https://github.com/xnhp0320)"

[menu]
  [[menu.main]]
    name = "Home"
    url = ""
    weight = 10

  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 20

[permalinks]
  note = "/post/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[markup]
  [[markup.highlit]]
    codeFences=false

[markup.goldmark.renderer]
  unsafe = true
  # Allows HTML in Markdown
